### ISSUE TITLE
Gpu load issues

### ISSUE THREAD

**Issue by libxzr** [zuk-devs/proprietary_vendor_zuk#2]
I find GPU have no load when even benching mark(gb4),and a lot of GPU's job are doing by CPUs thats why game is so lag.Please look into it.

See GPU load with Trepn Profiler

**Comment by libxzr** [comment]
!solved!

**Comment by subhajeetmuhuri** [comment]
@xzr467706992 would you mind saying how did you solve the issue? RenderScript scores are around 4000 instead of 7000 when lineage-15.1 branches are used.

**Comment by likanchen** [comment]
factory2vendor

**Comment by ghost** [comment]
It should be fixed with zuk-devs/android_device_zuk_msm8996-common@8499d57376cbdc3ed641e41e99dc00b36347eb04
