### ISSUE TITLE
the latest z2_plus's vendor has something wrong with brightness control

### ISSUE THREAD

**Issue by likanchen** [zuk-devs/proprietary_vendor_zuk#4]
The brightness control and some sensors are unuseable when I use the vendor to build z2_plus's LOS15.1. Branch:Lineage-15.1

**Comment by subhajeetmuhuri** [comment]
Revert https://github.com/zuk-devs/android_device_zuk_msm8996-common/commit/d216cf42b5c797af2cc5ef06fc6d0077f0594e0c

**Comment by ghost** [comment]
It should be fixed with zuk-devs/android_device_zuk_z2_plus@d0449a03d979c5222296805f384821e85157043e commit.
